### ISSUE TITLE
＿ Is not a usable character of JAVA

### ISSUE THREAD

**Issue by kts6528** [JPiere/JPBP#1]
https://github.com/JPiere/JPBP/blob/df80a619fac5794f78f03d4874087e3269cccb48/jpiere.base.plugin/src/jpiere/base/plugin/webui/apps/form/JPiereCreateFromShipment.java#L431

There are many others

**Comment by JPiere** [comment]
Thanks for reporting
https://github.com/JPiere/JPBP/commit/63214d7a63636c81d0f504fcbaa0a0b9c9ad8bb7
